import type { PipelineRun, PipelineStepRun, PlatformOverview, RunStatus } from "@/lib/contracts"

export const overviewFixture: PlatformOverview = {
  id: "province-warehouse",
  province: "Kho dữ liệu Sở Tài chính",
  source: "iMate · Văn bản điều hành",
  updatedAt: "21/08/2026 · 10:36",
  cleanRate: 95.47,
  managedRecords: 6141,
  databaseCount: 1,
  activeRuleGroups: 4,
  pendingIssues: 278,
  steps: [
    {
      id: 1,
      code: "B1",
      title: "Sao lưu và đóng băng dữ liệu gốc",
      description: "Lưu bản gốc bất biến tại Bronze, gắn checksum và dấu thời gian để có thể phát lại.",
      status: "healthy",
      statusLabel: "Ổn định",
      metric: "6.141",
      metricLabel: "bản ghi Bronze",
      actionLabel: "Xem dữ liệu gốc",
      lastUpdated: "10:34",
    },
    {
      id: 2,
      code: "B2",
      title: "Đánh giá chất lượng và phân loại lỗi",
      description: "Chạy bộ quy tắc chất lượng, phân nhóm lỗi và tính điểm theo mức độ ảnh hưởng.",
      status: "warning",
      statusLabel: "Cần chú ý",
      metric: "95,47%",
      metricLabel: "đạt quy tắc chấm điểm",
      actionLabel: "Mở màn đánh giá",
      lastUpdated: "10:35",
    },
    {
      id: 3,
      code: "B3",
      title: "Chuẩn hóa danh mục và định dạng",
      description: "Đưa mã nguồn về danh mục dùng chung; trường chưa khớp chờ steward quyết định.",
      status: "pending",
      statusLabel: "Chờ xử lý",
      metric: "278",
      metricLabel: "mã cần rà soát",
      actionLabel: "Xử lý mã chưa khớp",
      lastUpdated: "10:35",
    },
    {
      id: 4,
      code: "B4",
      title: "Xử lý trùng lặp",
      description: "Phát hiện trùng tuyệt đối và nghi trùng; không tự gộp khi chưa đủ căn cứ.",
      status: "healthy",
      statusLabel: "Ổn định",
      metric: "0",
      metricLabel: "trùng tuyệt đối",
      actionLabel: "Xem ứng viên trùng",
      lastUpdated: "10:35",
    },
    {
      id: 5,
      code: "B5",
      title: "Làm giàu từ nguồn chính thống",
      description: "Đối soát nguồn có thẩm quyền, bổ sung trường thiếu và lưu đầy đủ bằng chứng nguồn.",
      status: "healthy",
      statusLabel: "Sẵn sàng",
      metric: "4",
      metricLabel: "nguồn tham chiếu",
      actionLabel: "Xem nguồn chuẩn",
      lastUpdated: "10:35",
    },
    {
      id: 6,
      code: "B6",
      title: "Kiểm tra lại và phúc tra",
      description: "Chạy lại toàn bộ bộ quy tắc sau xử lý và ưu tiên phúc tra đơn vị có điểm thấp.",
      status: "running",
      statusLabel: "Đang chạy",
      metric: "27/27",
      metricLabel: "kiểm thử dbt đạt",
      actionLabel: "Theo dõi kiểm định",
      lastUpdated: "10:36",
    },
    {
      id: 7,
      code: "B7",
      title: "Duy trì dữ liệu sạch",
      description: "Theo dõi xu hướng, cảnh báo lỗi mới và gắn đầu mối chịu trách nhiệm theo từng nguồn.",
      status: "healthy",
      statusLabel: "Đang giám sát",
      metric: "0",
      metricLabel: "sự cố mở",
      actionLabel: "Mở giám sát",
      lastUpdated: "10:36",
    },
  ],
}

const fixtureStages = [
  ["01", 1, "Nguồn", "Khám phá thay đổi", "imate_01_discover"],
  ["02", 2, "Bronze", "Lưu bằng chứng nguyên bản", "imate_02_land_bronze"],
  ["03", 3, "Silver-1", "Trải phẳng nguyên văn", "imate_03_silver_one"],
  ["04", 4, "Silver-2", "Ép kiểu và tra danh mục", "imate_04_silver_two"],
  ["04b", 4, "Silver-2", "Cổng chất lượng", "imate_04b_quality_gate"],
  ["05", 5, "Gold", "Dựng mô hình phân tích", "imate_05_publish"],
  ["06", 6, "Serving", "Kiểm tra hợp đồng phục vụ", "imate_06_serving"],
  ["07", 7, "Khai thác", "Xuất báo cáo và API", "imate_07_report"],
] as const

function fixtureSteps(completedSteps: number, runStatus: RunStatus): PipelineStepRun[] {
  return fixtureStages.map(([code, stepNumber, title, phaseLabel, dagId]) => {
    let status: RunStatus = stepNumber <= completedSteps ? "success" : "waiting"
    if (stepNumber === completedSteps + 1 && runStatus === "failed") status = "failed"
    if (stepNumber === completedSteps + 1 && runStatus === "running") status = "running"
    return {
      code,
      stepNumber,
      title,
      phaseLabel,
      dagId,
      dagRunId: `fixture__${code}`,
      status,
      startedAt: status === "waiting" ? undefined : "2026-08-21T03:34:02Z",
      finishedAt: status === "success" ? "2026-08-21T03:36:12Z" : undefined,
      recordCount: status === "success" ? 6141 : 0,
      warningCount: status === "failed" ? 1 : 0,
      errorCount: status === "failed" ? 1 : 0,
    }
  })
}

export const pipelineRunsFixture: PipelineRun[] = [
  {
    id: "fixture-run-1",
    correlationId: "fixture::manual__2026-08-21T10:34:02",
    airflowRunId: "manual__2026-08-21T10:34:02",
    startedAt: "2026-08-21T03:34:02Z",
    finishedAt: "2026-08-21T03:36:12Z",
    status: "success",
    triggerType: "manual",
    initiatedBy: "airflow",
    scope: "iMate · toàn bộ chuỗi",
    completedSteps: 7,
    totalSteps: 7,
    recordCount: 6141,
    steps: fixtureSteps(7, "success"),
  },
  {
    id: "fixture-run-2",
    correlationId: "fixture::scheduled__2026-08-21T08:00:00",
    airflowRunId: "scheduled__2026-08-21T08:00:00",
    startedAt: "2026-08-21T01:00:00Z",
    finishedAt: "2026-08-21T01:02:19Z",
    status: "success",
    triggerType: "scheduled",
    initiatedBy: "Lịch 08:00",
    scope: "iMate · tăng dần",
    completedSteps: 7,
    totalSteps: 7,
    recordCount: 193,
    steps: fixtureSteps(7, "success"),
  },
  {
    id: "fixture-run-3",
    correlationId: "fixture::scheduled__2026-08-20T17:00:00",
    airflowRunId: "scheduled__2026-08-20T17:00:00",
    startedAt: "2026-08-20T10:00:00Z",
    finishedAt: "2026-08-20T10:01:43Z",
    status: "failed",
    triggerType: "scheduled",
    initiatedBy: "Lịch 17:00",
    scope: "iMate · tăng dần",
    completedSteps: 3,
    totalSteps: 7,
    recordCount: 0,
    steps: fixtureSteps(3, "failed"),
  },
]
